### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by keinstein** [lisjin/fca-viz#1]
Hi,

could you add license information to your repository?

I'm looking for some FCA code that can be used in a commertial sensor product and I prefer to use an OSS library that allows such applications. This would allow me to share my improvements of the code without the need to publish confidential data. If I wrote the code myself it is hard to argue that the company should publish its sources.

**Comment by lisjin** [comment]
Thanks for your interest. I've just added an MIT license, so feel free to use it as you please. I can also add a README within the next few days for instructions.

**Comment by lisjin** [comment]
I've just added a README - sorry for the delay. It is a bit of a hassle to set up, so I have been thinking about updating it to use a web interface instead. Let me know if you think this would be helpful, or if any issues pop up.
